src/hu/davecat/ulyssys/controller/UserController.java
package hu.davecat.ulyssys.controller;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;

import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;

import hu.davecat.ulyssys.entity.Type;
import hu.davecat.ulyssys.entity.User;
import hu.davecat.ulyssys.service.UserService;

@ManagedBean
public class UserController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ManagedProperty("#{userService}")
	UserService userService;

	private User loggedInUser;


	Authentication auth = SecurityContextHolder.getContext().getAuthentication();
	private String loggedInLoginname = auth.getName();

	@PostConstruct
	public void actualUser() {
		loggedInUser = userService.findUserByLoginName(loggedInLoginname);		

	}
		
	public String getUserMyApplicationsPage() {
		if (loggedInUser.getType().equals(Type.applicants)) {
			return "/secure/applicants/MyApplications.xhtml";
		} else {
			return "/secure/approver/MyApplications.xhtml";
		}
	}

	public String getUserApplicationApprovePage() {
		if (loggedInUser.getType().equals(Type.applicants)) {
			return "/secure/applicants/ApplicationApprove.xhtml";
		} else {
			return "/secure/approver/ApplicationApprove.xhtml";
		}
	}
	
	public User getLoggedInUser() {
		return loggedInUser;
	}

	public void setLoggedInUser(User loggedInUser) {
		this.loggedInUser = loggedInUser;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

}

WebContent/secure/applicants/ApplicationApprove.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="cs" />
	<link href="/css/screen.css" type="text/css" rel="stylesheet" media="screen,projection" />

	<title>ApplicationApprove</title>
</h:head>
<h:body>
	<div id="layout">

		<div id="header">

			<h1 id="logo">
				<a href="/secure/Succeed.xhtml" title="">JSF-TEST<span>.com</span></a>
			</h1>
			<hr class="noscreen" />

			<div id="navigation">
					<ul>
					<li><a href="#{userController.userMyApplicationsPage}" title="MY APPLICATIONS">MY APPLICATIONS</a></li>
					<li><a href="#{userController.userApplicationApprovePage}" title="APPLICATIONS APPROVE">APPLICATIONS APPROVE</a></li>
					<li><a href="/secure/Events.xhtml" title="EVENTS">EVENTS</a></li>
				</ul>
				<form action="${request.contextPath}/appLogout" method="POST">
					#{userController.loggedInUser.name} <input type="submit" value="Logout" /> <input type="hidden"
						name="${_csrf.parameterName}" value="${_csrf.token}" />
				</form>
			</div>
			<hr class="noscreen" />

		</div>
		<div id="main">
		<h1>
				<br />You can only see the approved applications, because you're not an approver!
			</h1>
			<p:dataTable var="appl" value="#{applicationController.approvedApplications}">
				<p:column headerText="User">
					<h:outputText value="#{appl.user.name}" />
				</p:column>
				<p:column headerText="Amount">
					<h:outputText value="#{appl.amount}" />
				</p:column>
				<p:column headerText="Status">
					<h:outputText value="#{applicationController.checkApprove(appl.approved)}" />
				</p:column>
			</p:dataTable>
		</div>
	</div>
	<div id="footer">
		<div id="footer-inside">
			<p align="center" id="copyright">
				2017 - <a href="https://www.linkedin.com/in/david-debreceni-140070145/">David Debreceni</a>
			</p>

		</div>
		<div style="clear: both;"></div>
	</div>
</h:body>
</html>

WebContent/secure/applicants/MyApplications.xhtml
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui">
<h:head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="cs" />
	<link href="/css/screen.css" type="text/css" rel="stylesheet" media="screen,projection" />

	<title>MyApplications</title>
</h:head>
<h:body>
	<div id="layout">

		<div id="header">

			<h1 id="logo">
				<a href="/secure/Succeed.xhtml" title="">JSF-TEST<span>.com</span></a>
			</h1>
			<hr class="noscreen" />

			<div id="navigation">
				<ul>
					<li><a href="#{userController.userMyApplicationsPage}" title="MY APPLICATIONS">MY APPLICATIONS</a></li>
					<li><a href="#{userController.userApplicationApprovePage}" title="APPLICATIONS APPROV">APPLICATIONS APPROVE</a></li>
					<li><a href="/secure/Events.xhtml" title="EVENTS">EVENTS</a></li>
				</ul>
				<form action="${request.contextPath}/appLogout" method="POST">
					#{userController.loggedInUser.name} <input type="submit" value="Logout" /> <input type="hidden"
						name="${_csrf.parameterName}" value="${_csrf.token}" />
				</form>
			</div>
			<hr class="noscreen" />

		</div>
		<div id="main">
			<h1>My Approved Applications #{userController.loggedInUser.enabled}</h1>
			<p:dataTable var="appl" value="#{applicationController.approvedApplicationsByUserName}">
				<p:column headerText="User">
					<h:outputText value="#{appl.user.name}" />
				</p:column>
				<p:column headerText="Amount">
					<h:outputText value="#{appl.amount}" />
				</p:column>
				<p:column headerText="Status">
					<h:outputText value="#{applicationController.checkApprove(appl.approved)}" />
				</p:column>
			</p:dataTable>
			<h1>My Editable Applications</h1>
			<p:dataTable var="appl" value="#{applicationController.notApprovedApplicationsByUserName}" id="applTable">
				<p:column headerText="User">
					<h:outputText value="#{appl.user.name}" />
				</p:column>
				<p:column headerText="Amount">
					<h:outputText value="#{appl.amount}" />
				</p:column>
				<p:column headerText="Status">
					<h:outputText value="#{applicationController.checkApprove(appl.approved)}" />
				</p:column>
				<p:column headerText="operations">
					<p:column>
						<h:form>
							<p:commandButton value="Edit" onclick="PF('dlg2').show();"
								action="#{applicationController.idForEditApplication(appl.id)}" />
							<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
						</h:form>
					</p:column>
					<p:dialog header="Edit Amount" widgetVar="dlg2" modal="true" height="100">
						<h:form id="applicationForm">
													
		New amount:
		<p:inputText autocomplete="false" required="true" value="#{applicationController.application.amount}" />
							<p:commandButton value="save" action="#{applicationController.editApplicationAmount()}"
								onclick="PF('dlg2').hide();" update="applicationForm, :applTable" />

							<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
						</h:form>
					</p:dialog>
				</p:column>
			</p:dataTable>
			<h:form id="applicationForm">
				<h2>New Application</h2>
				<p:panelGrid columns="3">
				
		Amount:
		<p:inputText autocomplete="false" required="true" value="#{applicationController.application.amount}" />
					<p:commandButton value="Create" action="#{applicationController.saveNewApplication()}"
						update="applicationForm, :applTable" />
				</p:panelGrid>
				<input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
			</h:form>

		</div>

	</div>
	<div id="footer">
		<div id="footer-inside">
			<p align="center" id="copyright">
				2017 - <a href="https://www.linkedin.com/in/david-debreceni-140070145/">David Debreceni</a>
			</p>

		</div>
		<div style="clear: both;"></div>
	</div>
</h:body>
</html>